version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: rangiffler-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - rangiffler_mysql_data:/var/lib/mysql
    networks:
      - rangiffler-network

volumes:
  rangiffler_mysql_data:

networks:
  rangiffler-network:
